/-
Copyright (c) 2025 Jonas van der Schaaf. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jonas van der Schaaf, Anish Rajeev
-/

module

public import Mathlib.ModelTheory.Types
public import Mathlib.Topology.Bases
public import Mathlib.Topology.Connected.TotallyDisconnected
public import Mathlib.Topology.Compactness.Compact
public import Mathlib.Topology.Connected.Separation
public import Mathlib.Topology.Baire.LocallyCompactRegular


public import Mathlib.Data.Finset.Insert
/-!
# Topology on the space of complete types

This file defines a topological structure on the type `CompleteType T α` (note that
these are types from model theory and not types from type theory). The topology
is generated by sets of the form `{p : CompleteType T α | ∃ φ, φ ∈ p}`.

Note that the contents of this file are separate from ModelTheory/Types.lean to avoid
importing files from the Topology folder there.
-/

open Set FirstOrder Language Theory CompleteType TopologicalSpace

namespace CompleteType

universe u

variable {L : Language} {T : L.Theory} {α : Type _}

instance : TopologicalSpace (CompleteType T α) := generateFrom (range typesWith)

public lemma typesWith_basis : IsTopologicalBasis (range (typesWith (α := α) (T := T))) where
  exists_subset_inter := by
    intro t₁ ⟨φ, ht₁⟩ t₂ ⟨ψ, ht₂⟩ x hx
    refine ⟨typesWith (φ ⊓ ψ), ⟨φ ⊓ ψ, rfl⟩, ?_⟩
    rw [typesWith_inf, ht₁, ht₂]
    exact ⟨hx, fun _ ↦ id⟩
  sUnion_eq := by
    rw [←Set.univ_subset_iff]
    exact Set.subset_sUnion_of_mem ⟨_, typesWith_top⟩
  eq_generateFrom := rfl

lemma typesWith_open (φ : (L[[α]]).Sentence) : IsOpen (typesWith (T := T) φ) :=
  isOpen_generateFrom_of_mem ⟨φ, rfl⟩

lemma typesWith_closed (φ : (L[[α]]).Sentence) : IsClosed (typesWith (T := T) φ) where
  isOpen_compl := by rw [←typesWith_compl]; exact typesWith_open _

lemma typesWith_clopen (φ : (L[[α]]).Sentence) : IsClopen (typesWith (T := T) φ) where
  left := typesWith_closed _
  right := typesWith_open _

instance : TotallySeparatedSpace (CompleteType T α) := by
  rw [totallySeparatedSpace_iff_exists_isClopen]
  intro p q hpq
  simp only [ne_eq, SetLike.ext_iff, not_forall, not_iff] at hpq
  obtain ⟨φ, hφ⟩ := hpq
  exact (mem_or_not_mem p φ).elim
    (fun h ↦ ⟨typesWith φ, typesWith_clopen _, h, by change ¬φ ∈ q; rwa [←hφ, not_not]⟩)
    (fun h ↦ ⟨
        typesWith ∼φ,
        typesWith_clopen _, h,
        by change ¬∼φ∈q; rwa [not_mem_iff,←hφ, not_not, ←not_mem_iff]
      ⟩)

instance : CompactSpace (T.CompleteType α) := by
  constructor
  rw[isCompact_iff_ultrafilter_le_nhds]
  intros F _
  refine ⟨⟨{φ | typesWith φ ∈ F}, ?_, ?_⟩, ?_⟩
  · intro φ x
    exact F.mem_of_superset Filter.univ_mem (fun p _ ↦ p.subset x)
  · rw [Theory.IsMaximal, Theory.isSatisfiable_iff_isFinitelySatisfiable]
    refine ⟨?_, ?_⟩
    · rw[Theory.IsFinitelySatisfiable]
      intro x hx
      have : ∀ φ ∈ x, typesWith φ ∈ F.toFilter := by intro φ hφ; exact hx hφ
      rw[←Filter.biInter_finset_mem x] at this
      obtain ⟨T, T_inter⟩ := F.neBot.nonempty_of_mem this
      have subset : SetLike.coe x ⊆ T.toTheory := by rwa[Set.mem_iInter₂] at T_inter
      exact Theory.IsSatisfiable.mono T.isMaximal'.1 subset
    · intro φ
      simp only [mem_setOf_eq, typesWith_compl]
      exact Ultrafilter.mem_or_compl_mem F (typesWith φ)
  · refine ⟨trivial, ?_⟩
    · rw [nhds_generateFrom]
      apply le_iInf₂
      intro _ h
      rw [Filter.le_principal_iff]
      obtain ⟨_, rfl⟩ := h.2
      exact h.1

instance : BaireSpace (T.CompleteType α) := BaireSpace.of_t2Space_locallyCompactSpace

/- Next steps in proving Omitting Types Theorem
   Based on the proof in Poizat's Model Theory textbook
-/

def countable_language (L : Language) : Prop :=
          ∀ n : ℕ, Countable (L.Functions n) ∧ Countable (L.Relations n)

def omits_type (M : T.ModelType) (p : T.CompleteType α) : Prop := p ∉ T.realizedTypes (α := α) M

abbrev ExpandedLanguage := L[[ℕ]]
local notation "L'" => @ExpandedLanguage L
def toL' : L →ᴸ L' := L.lhomWithConstants ℕ
local notation "T'" => toL'.onTheory T

/- TODO: Make the set of constants from Fin 1 to Fin n -/

noncomputable def existential_of_formula (φ : L'[[Fin 1]].Sentence) : L'[[Fin 1]].Sentence := by
  replace φ := ((L').lhomWithConstantsMap (fun i ↦ Sum.inr i) (β := Empty ⊕ (Fin 1))).onSentence φ
  replace φ := Formula.equivSentence.2 φ
  replace φ := Formula.iExs (α := Empty) (β := Fin 1) (L := L') φ
  exact ((L').lhomWithConstants (Fin 1)).onSentence φ

def replace_with_constant (φ : L'[[Fin 1]].Sentence) (c : ℕ) : L'[[Fin 1]].Sentence := by
  replace φ := Formula.equivSentence.2 φ
  replace φ := BoundedFormula.subst φ (fun _ => Constants.term (Sum.inr c)) (β := Fin 1)
  exact Formula.equivSentence.1 φ

def henkin_theory (φ : L[[Fin 1]].Sentence) : Set ((T').CompleteType (Fin 1)) := by
  replace φ : L'[[Fin 1]].Sentence := (toL'.addConstants (L := L) (Fin 1)).onSentence φ
  have φe : L'[[Fin 1]].Sentence := existential_of_formula φ
  exact {p : (T').CompleteType (Fin 1) | φe ∈ p → ∃ c : ℕ, replace_with_constant φ c ∈ p}

def henkin_dense : ∀ φ : L[[Fin 1]].Sentence,
                    Dense (X := (T').CompleteType (Fin 1)) (henkin_theory φ) := by
  intro φ
  let φ' := existential_of_formula ((toL'.addConstants (L := L) (Fin 1)).onSentence φ)
  rw[IsTopologicalBasis.dense_iff typesWith_basis]
  intro o hne ⟨p, hp⟩
  obtain ⟨ψ, rfl⟩ := hne
  let T'' := (((L').lhomWithConstants (Fin 1)).onTheory T')
  -- Case on whether ψ and φ' are consistent together
  by_cases h' : ({ψ, φ'} ∪ T'').IsSatisfiable
  /-
  This case is complicated, as I'm (pretty sure at least) that I have to find a fresh constant from
  ℕ (call it c) not used in φ' or ψ, and then redefine the model M got from h' to interpret c as x
  (where x is the value in the universe that satisfies the existential φ') and then show that
  {ψ, φ'} ∪ T'' is satisfied by this new model, and then finally get the complete type from it
  -/
  · obtain ⟨M⟩ := h'
    have h_ex : M ⊨ φ' := by
      have := M.is_model; simp at this
      exact this φ' (Or.inl (Or.inr (refl φ')))
    dsimp [φ', existential_of_formula] at h_ex
    have := LHom.realize_onSentence M.Carrier ((L').lhomWithConstants (Fin 1)) (Formula.iExs (Fin 1)
      (Formula.equivSentence.symm
        ((ExpandedLanguage.lhomWithConstantsMap fun i ↦ Sum.inr i).onSentence
          ((LHom.addConstants (Fin 1) toL').onSentence φ))))
    rw[this, Sentence.Realize, Formula.realize_iExs] at h_ex; clear this
    obtain ⟨x, hx⟩ := h_ex
    sorry
    -- If it is not consistent, this is the easy case since the implication is vacously true
  · use p
    rw[Set.mem_inter_iff]
    constructor
    · assumption
    · intro h; exfalso
      have subset : ({ψ, φ'} ∪ T'') ⊆ p := by
        intro x hx
        rw[Set.mem_union] at hx
        simp at hx
        rcases hx with (hx | hx) | hx
        · rw[hx]
          exact hp
        · rw[hx]
          exact h
        · exact (p.subset) hx
      have p_inconsistent : ¬p.toTheory.IsSatisfiable := by
        intro x; exact h' (IsSatisfiable.mono x subset)
      exact p_inconsistent (p.isMaximal.1)


end CompleteType
