/-
Copyright (c) 2025 Jonas van der Schaaf. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jonas van der Schaaf, Anish Rajeev
-/

module

public import Mathlib.ModelTheory.Types
public import Mathlib.Topology.Bases
public import Mathlib.Topology.Connected.TotallyDisconnected
public import Mathlib.Topology.Compactness.Compact
public import Mathlib.Topology.Connected.Separation
public import Mathlib.Topology.Baire.LocallyCompactRegular


public import Mathlib.Data.Finset.Insert
/-!
# Topology on the space of complete types

This file defines a topological structure on the type `CompleteType T α` (note that
these are types from model theory and not types from type theory). The topology
is generated by sets of the form `{p : CompleteType T α | ∃ φ, φ ∈ p}`.

Note that the contents of this file are separate from ModelTheory/Types.lean to avoid
importing files from the Topology folder there.
-/

open Set FirstOrder Language Theory CompleteType TopologicalSpace

namespace CompleteType

universe u

variable {L : Language} {T : L.Theory} {α : Type _}

instance : TopologicalSpace (CompleteType T α) := generateFrom (range typesWith)

public lemma typesWith_basis : IsTopologicalBasis (range (typesWith (α := α) (T := T))) where
  exists_subset_inter := by
    intro t₁ ⟨φ, ht₁⟩ t₂ ⟨ψ, ht₂⟩ x hx
    refine ⟨typesWith (φ ⊓ ψ), ⟨φ ⊓ ψ, rfl⟩, ?_⟩
    rw [typesWith_inf, ht₁, ht₂]
    exact ⟨hx, fun _ ↦ id⟩
  sUnion_eq := by
    rw [←Set.univ_subset_iff]
    exact Set.subset_sUnion_of_mem ⟨_, typesWith_top⟩
  eq_generateFrom := rfl

lemma typesWith_open (φ : (L[[α]]).Sentence) : IsOpen (typesWith (T := T) φ) :=
  isOpen_generateFrom_of_mem ⟨φ, rfl⟩

lemma typesWith_closed (φ : (L[[α]]).Sentence) : IsClosed (typesWith (T := T) φ) where
  isOpen_compl := by rw [←typesWith_compl]; exact typesWith_open _

lemma typesWith_clopen (φ : (L[[α]]).Sentence) : IsClopen (typesWith (T := T) φ) where
  left := typesWith_closed _
  right := typesWith_open _

instance : TotallySeparatedSpace (CompleteType T α) := by
  rw [totallySeparatedSpace_iff_exists_isClopen]
  intro p q hpq
  simp only [ne_eq, SetLike.ext_iff, not_forall, not_iff] at hpq
  obtain ⟨φ, hφ⟩ := hpq
  exact (mem_or_not_mem p φ).elim
    (fun h ↦ ⟨typesWith φ, typesWith_clopen _, h, by change ¬φ ∈ q; rwa [←hφ, not_not]⟩)
    (fun h ↦ ⟨
        typesWith ∼φ,
        typesWith_clopen _, h,
        by change ¬∼φ∈q; rwa [not_mem_iff,←hφ, not_not, ←not_mem_iff]
      ⟩)

instance : CompactSpace (T.CompleteType α) := by
  constructor
  rw[isCompact_iff_ultrafilter_le_nhds]
  intros F _
  refine ⟨⟨{φ | typesWith φ ∈ F}, ?_, ?_⟩, ?_⟩
  · intro φ x
    exact F.mem_of_superset Filter.univ_mem (fun p _ ↦ p.subset x)
  · rw [Theory.IsMaximal, Theory.isSatisfiable_iff_isFinitelySatisfiable]
    refine ⟨?_, ?_⟩
    · rw[Theory.IsFinitelySatisfiable]
      intro x hx
      have : ∀ φ ∈ x, typesWith φ ∈ F.toFilter := by intro φ hφ; exact hx hφ
      rw[←Filter.biInter_finset_mem x] at this
      obtain ⟨T, T_inter⟩ := F.neBot.nonempty_of_mem this
      have subset : SetLike.coe x ⊆ T.toTheory := by rwa[Set.mem_iInter₂] at T_inter
      exact Theory.IsSatisfiable.mono T.isMaximal'.1 subset
    · intro φ
      simp only [mem_setOf_eq, typesWith_compl]
      exact Ultrafilter.mem_or_compl_mem F (typesWith φ)
  · refine ⟨trivial, ?_⟩
    · rw [nhds_generateFrom]
      apply le_iInf₂
      intro _ h
      rw [Filter.le_principal_iff]
      obtain ⟨_, rfl⟩ := h.2
      exact h.1

instance : BaireSpace (T.CompleteType α) := BaireSpace.of_t2Space_locallyCompactSpace

/- Next steps in proving Omitting Types Theorem
   Based on the proof in Poizat's Model Theory textbook
-/

def countable_language (L : Language) : Prop :=
          ∀ n : ℕ, Countable (L.Functions n) ∧ Countable (L.Relations n)

def omits_type (M : T.ModelType) (p : T.CompleteType α) : Prop := p ∉ T.realizedTypes (α := α) M

abbrev ExpandedLanguage := L[[ℕ]]
local notation "L'" => @ExpandedLanguage L
def toL' : L →ᴸ L' := L.lhomWithConstants ℕ
local notation "T'" => toL'.onTheory T

/- TODO: Make the set of constants from Fin 1 to Fin n -/

noncomputable def existential_of_formula (φ : L'[[Fin 1]].Sentence) : L'[[Fin 1]].Sentence := by
  replace φ := ((L').lhomWithConstantsMap (fun i ↦ Sum.inr i) (β := Empty ⊕ (Fin 1))).onSentence φ
  replace φ := Formula.equivSentence.2 φ
  replace φ := Formula.iExs (α := Empty) (β := Fin 1) (L := L') φ
  exact ((L').lhomWithConstants (Fin 1)).onSentence φ

def replace_with_constant (φ : L'[[Fin 1]].Sentence) (c : Fin 1 → ℕ) : (L').Sentence :=
  (Formula.equivSentence.2 φ).subst (β := Empty) (fun i ↦ Constants.term (Sum.inr (c i)))

def henkinTheory (φ : L[[Fin 1]].Sentence) : Set ((T').CompleteType (Fin 1)) := by
  replace φ : L'[[Fin 1]].Sentence := (toL'.addConstants (L := L) (Fin 1)).onSentence φ
  have φe : L'[[Fin 1]].Sentence := existential_of_formula φ
  exact { p : (T').CompleteType (Fin 1) | φe ∈ p →
        ∃ c : (Fin 1 → ℕ), ((L').lhomWithConstants (Fin 1)).onSentence
              (replace_with_constant φ c) ∈ p }

def constantsIn_term {α : Type*} (t : L'[[Fin 1]].Term α) : Finset ℕ :=
  match t with
  | var _ => {}
  | func (l := l) sym ts =>
    match l, sym with
    | 0, Sum.inl (Sum.inr c) => {c}
    | 0, _ => {}
    | _, _ => Finset.biUnion Finset.univ (fun i ↦ constantsIn_term (ts i))

def constantsIn {α : Type*} {n : ℕ} (φ : L'[[Fin 1]].BoundedFormula α n) : Finset ℕ :=
  match φ with
  | BoundedFormula.falsum => {}
  | BoundedFormula.equal t₁ t₂ => (constantsIn_term t₁) ∪ (constantsIn_term t₂)
  | BoundedFormula.rel _ ts => Finset.biUnion Finset.univ (fun i ↦ constantsIn_term (ts i))
  | BoundedFormula.imp f₁ f₂ => (constantsIn f₁) ∪ (constantsIn f₂)
  | BoundedFormula.all f => constantsIn f

noncomputable def updateConstantInterpretation {M : Type*} (S : L'[[Fin 1]].Structure M)
  (c : L'[[Fin 1]].Constants) (new_val : M) : L'[[Fin 1]].Structure M :=
  { S with
      funMap {n} :=
        have := Classical.propDecidable
        match n with
        | 0 => Function.update S.funMap c (fun _ ↦ new_val)
        | _ => S.funMap }

lemma coincidence_term {M : Type*} (S : L'[[Fin 1]].Structure M) (t : L'[[Fin 1]].Term (α))
  (v : α → M) (c : ℕ) (h : c ∉ constantsIn_term t) (new_val : M) :
  @Term.realize _ _ S _ v t =
  @Term.realize _ _ (updateConstantInterpretation S (Sum.inl (Sum.inr c)) new_val) _ v t := by
    let M' := (updateConstantInterpretation S (Sum.inl (Sum.inr c)) new_val)
    induction t with
    | var x => simp
    | func f ts ih =>
      simp [updateConstantInterpretation]
      split
      next =>
        simp[Function.update_apply]
        split
        next hfc =>
          subst hfc
          unfold constantsIn_term at h
          simp at h
        next hfnc =>
          congr with i
          exact i.elim0
      next _ _ h' =>
        congr with i; apply ih
        unfold constantsIn_term at h
        split at h <;> repeat contradiction
        · rw[Finset.mem_biUnion] at h
          push_neg at h
          exact h i (by simp)

lemma coincidence {n} {M : Type*} (S : L'[[Fin 1]].Structure M) (φ : L'[[Fin 1]].BoundedFormula α n)
  (c : ℕ) (v : α → M) (xs : Fin n → M) (h : c ∉ constantsIn φ) (new_val : M) :
  @φ.Realize _ _ S _ _ v xs ↔
  @φ.Realize _ _ (updateConstantInterpretation S (Sum.inl (Sum.inr c)) new_val) _ _ v xs := by
    let M' := (updateConstantInterpretation S (Sum.inl (Sum.inr c)) new_val)
    induction φ with
    | falsum => simp [BoundedFormula.Realize]
    | equal t₁ t₂ =>
      simp[constantsIn] at h
      have h₁ := coincidence_term S t₁ (Sum.elim v xs) c h.1 new_val
      have h₂ := coincidence_term S t₂ (Sum.elim v xs) c h.2 new_val
      simp[BoundedFormula.Realize, h₁, h₂]
    | rel R ts =>
      simp[constantsIn] at h
      simp[BoundedFormula.Realize]
      have hᵢ : (fun i ↦ @Term.realize _ _ S _ (Sum.elim v xs) (ts i)) =
               (fun i ↦ @Term.realize _ _ M' _ (Sum.elim v xs) (ts i)) := by
              have := fun i ↦ coincidence_term S (ts i) (Sum.elim v xs) c (h i) new_val
              congr with i; exact this i
      simp[hᵢ, updateConstantInterpretation]
    | imp f₁ f₂ ih₁ ih₂ =>
      simp[constantsIn] at h
      have h₁ := ih₁ xs h.1
      have h₂ := ih₂ xs h.2
      simp_rw[BoundedFormula.Realize, h₁, h₂]
    | all f ih =>
      simp[constantsIn] at h
      simp[BoundedFormula.Realize]
      apply forall_congr'; intro x
      exact ih (Fin.snoc xs x) h

def Structure.toCompleteType {M : Type*} [L[[α]].Structure M] [Nonempty M]
    (h : M ⊨ (L.lhomWithConstants α).onTheory T) : T.CompleteType α where
  toTheory := { φ | M ⊨ φ }
  subset' := fun φ ↦ fun hφ ↦ h.realize_of_mem φ hφ
  isMaximal' := by
    constructor
    · haveI : M ⊨ { φ | @Sentence.Realize (L[[α]]) M _ φ } := ⟨fun _ hx ↦ hx⟩
      exact @Model.isSatisfiable (L[[α]]) { φ | M ⊨ φ } M _ _ _
    · intro φ
      simp;
      exact Classical.em (M ⊨ φ)

def henkinDense : ∀ φ : L[[Fin 1]].Sentence,
                    Dense (X := (T').CompleteType (Fin 1)) (henkinTheory φ) := by
  intro φ
  let φ' := existential_of_formula ((toL'.addConstants (L := L) (Fin 1)).onSentence φ)
  rw[IsTopologicalBasis.dense_iff typesWith_basis]
  intro o hne ⟨p, hp⟩
  obtain ⟨ψ, rfl⟩ := hne
  let T'' := (((L').lhomWithConstants (Fin 1)).onTheory T')
  -- Case on whether ψ and φ' are consistent together
  by_cases h' : ({ψ, φ'} ∪ T'').IsSatisfiable
  · obtain ⟨M⟩ := h'
    have h_ex : M ⊨ φ' := by
      have := M.is_model; simp at this
      exact this φ' (Or.inl (Or.inr (refl φ')))
    dsimp [φ', existential_of_formula] at h_ex
    have := LHom.realize_onSentence M.Carrier ((L').lhomWithConstants (Fin 1)) (Formula.iExs (Fin 1)
      (Formula.equivSentence.symm
        ((ExpandedLanguage.lhomWithConstantsMap fun i ↦ Sum.inr i).onSentence
          ((LHom.addConstants (Fin 1) toL').onSentence φ))))
    rw[this, Sentence.Realize, Formula.realize_iExs] at h_ex; clear this
    obtain ⟨x, hx⟩ := h_ex
    have c := ((constantsIn φ' ∪ constantsIn ψ).max.getD 0) + 1
    let S' := updateConstantInterpretation M.struc (Sum.inl (Sum.inr c)) (x 0)
    have hc₁ : c ∉ (constantsIn φ') := sorry
    have hc₂ : c ∉ (constantsIn ψ) := sorry
    have hc₃ : ∀ φ ∈ T'', c ∉ (constantsIn φ) := sorry
    have hM' : @Theory.Model (L'[[Fin 1]]) (M.Carrier) S' ({ψ, φ'} ∪ T'') := by
      simp; intro φ h_in
      rcases h_in with ((h | h) | h)
      · rw[h]
        have := coincidence M.struc ψ c (default : _ → M) default hc₂ (x 0)
        have hψ : @Sentence.Realize (L'[[Fin 1]]) (M.Carrier) M.struc ψ := by
          have := M.is_model; simp at this
          exact this ψ (Or.inl (Or.inl (refl ψ)))
        exact this.1 hψ
      · rw[h]
        have := coincidence M.struc φ' c (default : _ → M) default hc₁ (x 0)
        have hφ' : @Sentence.Realize (L'[[Fin 1]]) (M.Carrier) M.struc φ' := by
          have := M.is_model; simp at this
          exact this φ' (Or.inl (Or.inr (refl φ')))
        exact this.1 hφ'
      · have := coincidence M.struc φ c (default : _ → M) default (hc₃ φ h) (x 0)
        have hφ : @Sentence.Realize (L'[[Fin 1]]) (M.Carrier) M.struc φ := by
          have := M.is_model; simp at this
          exact this φ (Or.inr h)
        exact this.1 hφ
    have := ((@Theory.model_union_iff (L'[[Fin 1]]) (M.Carrier) S' {ψ, φ'} T'').1 hM').2
    let q := Structure.toCompleteType this
    use q
    constructor
    · change ψ ∈ q.toTheory
      dsimp[q, Structure.toCompleteType]
      exact hM'.realize_of_mem ψ (by simp)
    · dsimp[henkinTheory, Structure.toCompleteType]
      intro _
      use c
      change _ ∈ q.toTheory
      simp[q, Structure.toCompleteType]
      let lowerStruct : (L').Structure M := ((L').lhomWithConstants (Fin 1)).reduct M
      haveI := lowerStruct; clear this
      haveI : (ExpandedLanguage.lhomWithConstants (Fin 1)).IsExpansionOn M :=
              LHom.isExpansionOn_reduct ((L').lhomWithConstants (Fin 1)) M.Carrier
      rw[LHom.realize_onSentence M.Carrier
            ((L').lhomWithConstants (Fin 1))
            (replace_with_constant ((LHom.addConstants (Fin 1) toL').onSentence φ) ↑c)]
      rw[Sentence.Realize, Formula.Realize, replace_with_constant, BoundedFormula.realize_subst]
      simp
      have := Formula.realize_equivSentence_symm
              M.Carrier
              ((LHom.addConstants (Fin 1) toL').onSentence φ)
              (fun i ↦ (L').constantMap (Sum.inr c))
      dsimp[Formula.Realize] at this
      simp[this, Sentence.Realize, Formula.Realize]
      sorry
  · use p
    rw[Set.mem_inter_iff]
    constructor
    · assumption
    · intro h; exfalso
      have subset : ({ψ, φ'} ∪ T'') ⊆ p := by
        intro x hx
        rw[Set.mem_union] at hx
        simp at hx
        rcases hx with (hx | hx) | hx
        · rw[hx]
          exact hp
        · rw[hx]
          exact h
        · exact (p.subset) hx
      have p_inconsistent : ¬p.toTheory.IsSatisfiable := by
        intro x; exact h' (IsSatisfiable.mono x subset)
      exact p_inconsistent (p.isMaximal.1)


end CompleteType
